name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
resolution: workspace

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  better_bus_core: 1.0.0
  sqlite3: ^2.7.4

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
